### ISSUE TITLE
Function download_metadata() causes 'OSError: [Errno 24] Too many open files' due to os.popen(cmd) calls

### ISSUE THREAD

**Issue by Sam-Koehler** [ATCC-Bioinformatics/genome_portal_api#27]
**Issue**
Hello! Attempting to extract meta data for many genomes (>4 pages worth) using the function `download_metadata()` results in the following error message:

```
Traceback (most recent call last):
  File "path/to/current/code.py", line 120, in <module>
    retrieve_atcc_info(dir_out=file_out, genomes=all_genomes_results, jwt=jwt)

  File "path/to/current/code.py", line 92, in retrieve_atcc_info
    assembly_metadata = download_metadata(jwt=jwt, id=genome['id'], )

  File "mamba/path/to/genome_portal_api/genome_portal_api.py", line 212, in download_metadata
    result = os.popen(cmd).read()

  File "mamba/path/to/os.py", line 983, in popen
    proc = subprocess.Popen(cmd,

  File "mamba/path/to/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "mamba/path/to/subprocess.py", line 1748, in _execute_child
    errpipe_read, errpipe_write = os.pipe()

OSError: [Errno 24] Too many open files
```

**Code to Reproduce**
The following code produced the error for me. *Description: This script goes page-by-page through the ATCC databases, using `download_all_genomes()` to extract all genome IDs for a given page. It then iterates through these genome IDs and extracts meta data (ATCC genome name) using function `download_metadata().*

```
## ___________________________________________________________________________
## Globals

## JWT (get fresh one here: https://genomes.atcc.org/profile)
jwt = "<enter_jwt_string_here>"



## ___________________________________________________________________________
## Packages

from genome_portal_api import *
import os



## ___________________________________________________________________________
## API

## Initialize Variables
page = 0

## Iteratively browse pages until blank page is reached
while True:
    
    ## Collect list of genomes on current page
    page +=1
    print(page)
    all_genomes_results = download_all_genomes(jwt=jwt, page=page)

    ## Identify if last page has been reached (download_all_genomes returns Nonetype object)
    if all_genomes_results is not None:

        ## Iterate through genomes on current page
        for genome in all_genomes_results:

            ## Retrieve meta data
            assembly_metadata = download_metadata(jwt=jwt, id=genome['id'])

            ## Gather target meta data statistic(s)s
            atcc_name         = str(assembly_metadata['name'])

    else:
        break
```

**Error Explanation**
I suspect that the `os.popen()` command being repeatedly called via the function `download_metadata()` results in opened files that are never closed, leading to the error `OSError: [Errno 24] Too many open files`.

**Proposed solution**
I was able to resolve this issue by modifying the function `download_metadata()` to close each opened file(s) after it is called as follows:

*Original Function*
```
...
cmd += " 2> /dev/null"
try:
    result = os.popen(cmd).read()
    if "Not found." in result:
        raise emptyResultsError(message)
    else:
        data = json.loads(result)
        return data
...
```

*Modified Function*
```
...
cmd += " 2> /dev/null"
try:
    preresult = os.popen(cmd)
    result = preresult.read()
    if "Not found." in result:
        raise emptyResultsError(message)
else:
      data = json.loads(result)
      preresult.close()
      return data
...
```

**Comment by josephpetrone** [comment]
Thank you for bringing this to our attention and providing a proposed solution! We recently underwent a large development cycle of the API scripts, and have addressed this particular issue in the [V1.0.0](https://github.com/ATCC-Bioinformatics/genome_portal_api/releases/tag/v1.0.0) production release. 

To address the `OSError: [Errno 24] Too many open files`, we implemented a similar strategy as you suggested by closing the file after each attempt to prevent file descriptor leakage. This should now eliminate this issue when querying a large portion of the collection.

Thank you for using the ATCC Genome Portal API!
